# Generated by Django 4.2.20 on 2025-04-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastevent',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
