# Generated by Django 4.2.20 on 2025-04-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_pastevent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='band.pastevent'),
        ),
    ]
