# Generated by Django 4.2.20 on 2025-04-23 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band', '0004_remove_likes_user_comments_user_alter_bookings_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='event',
        ),
        migrations.AddField(
            model_name='bookings',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
