# Generated by Django 4.2.20 on 2025-04-25 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band', '0006_likes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/event_images/'),
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/event_images/'),
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='event_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
