# Generated by Django 4.2.20 on 2025-04-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0007_bookings_event_image_upcomingevent_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
