# Generated by Django 4.2.20 on 2025-04-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0009_alter_bookings_event_image_alter_upcomingevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastevent',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
