# Generated by Django 4.2.20 on 2025-04-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0010_pastevent_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastevent',
            old_name='event_image',
            new_name='image',
        ),
    ]
