# Generated by Django 4.2.20 on 2025-04-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0011_rename_event_image_pastevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
