# Generated by Django 4.2.20 on 2025-04-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0012_comments_date_comments_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='band_response',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
    ]
