# Generated by Django 4.2.20 on 2025-04-26 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band', '0013_bookings_band_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='upcoming_event_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
